### ISSUE TITLE
Localization Support

### ISSUE THREAD

**Issue by nico-bellante** [OfficeDev/script-lab#26]

**Comment by Zlatkovsky** [comment]
Started a bit of work on it (with support for making "fake" string) while on the airplane.  That work is stashed away at <https://github.com/OfficeDev/script-lab/tree/zlatkovsky/localization-start>

**Comment by gergzk** [comment]
Can you make sure you do this in a way that’s compatible with the office
loc pipeline?

**Comment by Zlatkovsky** [comment]
Yep, for sure.  There are several steps along the way:

1. Set up infrastructure on the JS side (e.g., to look up what is the Office current display language or setting value; to transfer this information from editor to runner; to have ability to have fake strings, which is what I have in that branch for now; etc)
2. Create an interface for the strings, as well as implementation files for each of the languages.  That's the part that we'll want to make compatible with the loc pipeline, though I expect that JSON is one of the many formats they use -- so something like what we have today in Script Lab 2017, maybe as a flat JSON file, should work.
3. Tokenize all of the strings that we use all over the UI, to make use of the localization.

**Comment by gergzk** [comment]
The way you access the strings might be a bit different, and I doubt you’ll
need the interface. The en-us bundle should serve as that. I would defer
this work til after we have moved out build to azure

**Comment by Zlatkovsky** [comment]
I put it into the "near-future" bucket for now.  I'm not going to be working on it immediately, but at the same time, I don't think we should wait too long on this, since it is feature take-back; and since, if I do the initial setup, others can help contribute to the effort (esp with "3.", which will take some time).

The interface would still be useful for strong typing on the TS side  (e.g., inside a React component, being able to do `<div>{getString("ok")}</div>`)

In my mind, the Office loc system is something we obviously need to scale out to the 20 or however many languages, but to get us back to the previously-localized state shouldn't require anything specific.  And when I talked to Mat from Insights team, it sounded like they were essentially using the same thing that we were in Script Lab, even with the Office loc process.  So I'll definitely look at what the Loc system requires, but I don't think we need to wait to be in Azure or to hook up with Office loc to do this work.  Even just getting tokanization in place would already be a good thing to do ahead of time, rather than continuing to scatter English all over the React markup in a non-traceable way.  It also would make it easier to have string review even for the English strings, to make sure that we are consistent with the Microsoft guidelines for UI.

**Comment by wandyezj** [comment]
Closing stale issues.
