### ISSUE TITLE
Add tooltip to Solution Properties of Header

### ISSUE THREAD

**Issue by nico-bellante** [OfficeDev/script-lab#324]
Currently, hovering on the title gives no tooltip.

**Comment by nico-bellante** [comment]
![image](https://user-images.githubusercontent.com/35939126/51275089-cfd99a00-1985-11e9-839a-7ab966358ca6.png)

I believe this is already working by default...

**Comment by Zlatkovsky** [comment]
It looks like in IE and Edge, the tooltip sometimes shows up, but sometimes doesn't -- somewhat non-deterministically.  Hovering back and forth doesn't fix it (once it stops showing, it generally doesn't try showing again) -- but clicking on the editor first and *then* returning to hover on the header does tend to bring it back.  Weird.

We may want to redirect to Fabric team.

The other thing for us to think through is whether the tooltip should say the snippet name (e.g., "Blank Snippet") or whether it should say what the action does ("Rename Snippet").  And even in full mode, when it says "Blank Snippet", can we make it so that hovering on the text offers a "Rename" in the tooltip?  Or can full-text labels not have a tooltip?

**Comment by wandyezj** [comment]
Obsolete.
