### ISSUE TITLE
CORS issue on ajax call

### ISSUE THREAD

**Issue by BartNetJS** [OfficeDev/script-lab#366]
Hi, I try to execute a rest call to an external endpoint, like this
```
$.ajax({
            url: "https://jsonplaceholder.typicode.com/posts/1",
            dataType: 'JSON',
            headers: {
              'Authorization': 'Basic blablabla',
            })....
```
Above is working fine. But on a end point where CORS is enabled, I got a xhr.readyState 0 back.
So two questions:
1. How can I debug the script's? (I cannot set break points)
2. Can I avoid the CORS issues? (I'm not the owner of the end point)

**Comment by Zlatkovsky** [comment]
@BartNetJS , I'm on the fence for whether this question is a GitHub issue vs. something that should be asked on StackOverflow.  But I'm leaning towards the latter.

That way, instead of the issue getting closed and lost forever, folks will continue being able to find it.

Would you mind asking the question on StackOverflow instead, tagging with "office-js" and "scriptlab" (not-yet-existent tag).  If you don't have enough StackOverflow reputation to create a tag, that's OK, just do "office-js" only, and I'll create the latter.

Thanks!

**Comment by Zlatkovsky** [comment]
(BTW, I would recommend asking it as two separate questions:  one about how to debug, and one about what to do about CORS, as they are sort of two separate topics).

**Comment by BartNetJS** [comment]
tx for the tips @Zlatkovsky

**Comment by BartNetJS** [comment]
link to the question on stackoverflow: http://stackoverflow.com/questions/43503737/cors-issue-on-ajax-call-in-scriptlab

@Zlatkovsky I indeed cannot add a new tag

**Comment by Zlatkovsky** [comment]
Answered the question on StackOverflow.  Closing this issue.

Btw, I see that on the stackoverflow question you didn't ask about debugging in scriptlab.  If you are interested, ask it as a separate question, and I can offer some pointers.
