### ISSUE TITLE
Method Word.body.search() doesn't find matching texts in footnotes/endnotes

### ISSUE THREAD

**Issue by costashu** [OfficeDev/script-lab#454]
Word documents have such a significant feature as footnotes/endnotes. In Word UI searching finds matching text in them, but method doesn't. To reproduce, use the attached document [footendnote.docx](https://github.com/OfficeDev/script-lab/files/1097705/footendnote.docx) and your sample Search (not using setup):
![search](https://user-images.githubusercontent.com/13196290/27481428-3957f43c-5825-11e7-90ff-06213f58aa99.png)
PS. Also, the text of footnotes/endnotes is not returned by any other methods.

**Comment by costashu** [comment]
Dear developers! If this issue is irrelevant here, where can I post it?

**Comment by jakobpn** [comment]
@JuaneloJuanelo, can you help take a look at this question?

**Comment by Zlatkovsky** [comment]
But to answer the question generally, you're welcome to report office.js bugs and questions using stock overflow, tagging the questions with "office-js"

**Comment by costashu** [comment]
Thanks for advice. Maybe I do it.

**Comment by Zlatkovsky** [comment]
@costashu , it doesn't look like this issue has received attention here, partly because it's not getting the right visibility while it's under "Script Lab", when in reality it is an API issue. Let me go ahead and close it, and encourage you to open up a question on stack overflow and/or open an issue on https://github.com/OfficeDev/office-js/issues

**Comment by costashu** [comment]
Thanks for the link.
