### ISSUE TITLE
Noticeable lag when editing libraries

### ISSUE THREAD

**Issue by AlexJerabek** [OfficeDev/script-lab#478]
### Bug Report

- **Host**: Excel
- **OS**: Windows 10
- **Browser**: N/A (win32)
- **Environment**: Beta

#### Expected behavior:

I can type in the "Libraries" text pane without have my keystrokes lag.

#### Actual behavior:

There is a noticeable delay between characters showing up on the screen.

#### Steps to Reproduce:

1. Replace the top two lines of the "Libraries" pane with
```
https://appsforoffice.microsoft.com/lib/1/hosted/office.js
https://appsforoffice.microsoft.com/lib/1/hosted/office.d.ts
```
2. Replace `1` with `beta`, using the keyboard to type out the characters.

**Comment by Zlatkovsky** [comment]
I'm starting to run into this too.  Moving back to 1.2

@nico-bellante , I think the main issue is that as soon as you edit anything, we try to fetch the new libraries.  I think for d.ts, we should only do that **after the user switches back to the "script" tab**.  Otherwise it's slow and wasteful.

We should also, if we're not already, make sure that we're only making the requests for:
1. non-duplicates
2. if we don't already have IntelliSense for this very string
