### ISSUE TITLE
Provide option to update existing snippet when importing a snippet from Github

### ISSUE THREAD

**Issue by jakobpn** [OfficeDev/script-lab#616]
![image](https://user-images.githubusercontent.com/13109307/30393565-6fd2a9c2-9875-11e7-82c2-870eeff9c427.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

## Useful logs

- [ ] Fiddler traces
- [ ] Console errors
- [ ] Screenshots
- [ ] Clip or GIFs

**Comment by Zlatkovsky** [comment]
It's actually **by design**.  Rationale:

* Most of the time (unless you're moving back and forth across computers), your local machine will have a newer version than the shared gist, not the other way around.  So most of the time this isn't a scenario.
* In my envisionment of the flow, I assumed that the user would generally switch to the existing snippet first, see what it's like -- and if they want to overwrite, click "delete", which will delete the snippet and bring up the import page with the URL same as before, so it's just one more click away.
* What if you have multiple snippets based on the same gist?  If we had a "replace" option, which one would it replace (or would we only show that option when there is 1 and only 1?  but that's a bit odd too...)?

**Comment by Zlatkovsky** [comment]
Reopening.
For the 3rd bullet point (what if have multiple), decision is to only show this button IFFF there is just one matching snippet.
