### ISSUE TITLE
When Script Lab is pinned in Outlook, snippet continues to run against original email

### ISSUE THREAD

**Issue by ElizabethSamuel-MSFT** [OfficeDev/script-lab#704]
### Bug Report

- **Host**: OUTLOOK
- **OS**: Windows
- **Browser**: 
- **Environment**: alpha

#### Expected behavior:

When item changes, Script Lab should refresh or get data for new item

#### Actual behavior:

When item changes, Script Lab continues to run against old item

#### Steps to Reproduce:

1. Open message in Reading pane
2. Click run to open Script Lab add-in
3. Pin Script Lab add-in
4. Switch to a new message

**Comment by nico-bellante** [comment]
Is this a Script Lab issue, or an Office.js for Outlook issue? @Andrew-MS

**Comment by ElizabethSamuel-MSFT** [comment]
Looks like pinning isn't fully implemented. See [article](https://docs.microsoft.com/en-us/outlook/add-ins/pinnable-taskpane) for more details.

**Comment by ElizabethSamuel-MSFT** [comment]
I discovered this bug would cause the Outlook add-in to fail [AppSource validation](https://docs.microsoft.com/en-us/office/dev/store/validation-policies). See section 4.12.1.

![image](https://user-images.githubusercontent.com/28541963/70643634-35fe8980-1bf6-11ea-967e-9d4ed5b68cc3.png)

**Comment by TCourtneyOwen** [comment]
@ElizabethSamuel-MSFT Looking into this issue as part of our quarterly work to get ScriptLab working with Outlook

**Comment by TCourtneyOwen** [comment]
Confirmed that this behavior is not unique to ScriptLab.  If I load a taskpane app from https://github.com/OfficeDev/Office-Addin-TaskPane in Outlook, open the taskpane in reading view and then change to a new mail while in reading view, the taskpane closes just as it does for ScriptLab

**Comment by TCourtneyOwen** [comment]
@ElizabethSamuel-MSFT OK, I was able to update one of the code sample (get sender) so that it picks up the context shift when the taskpane is pinned.  I am wondering if this is something we want to update in each relevant sample, or should this be done at a core ScriptLab level.  If at the core level, I will have to do more research to figure out how to make this work

**Comment by ElizabethSamuel-MSFT** [comment]
@TCourtneyOwen My thought is that the add-in (Script Lab) should support pinning, particularly for AppSource validation to succeed.

**Comment by annich-MS** [comment]
There's 2 schools of thought here, and I'm not 100% on which is better, but I think it's important that we acknowledge both.

1. For users who don't care about pinning functionality, being able to click on different messages to see different results from their snippet without having to write the pinning boilerplate is a plus.
2. For users who are specifically testing something around pinning, having the code done for them may prevent them from testing the scenario themselves and finding the issue they are facing (if they are using ScriptLab in an MVP debug use case)

Optimally, I'd love to have a "Pinning Scenario" flag that toggles if we handle the pinning for them, but off the top of my head, I don't know if that's feasible.

**Comment by TCourtneyOwen** [comment]
@annich-MS I haven't been able to find away to determine if pinning is enabled at runtime. Any idea if this is possible?  If so, then we can detect this and perhaps inject js in the user-defined code to handle the context switching. Here's an example of code that handles the context switching:

$("#get-from").click(getSend);

function getSend() {
  Office.context.mailbox.addHandlerAsync(Office.EventType.ItemChanged, itemChanged);
  // UpdateTaskPaneUI(Office.context.mailbox.item);
  var msgFrom = Office.context.mailbox.item.from;
  console.log("Message received from: " + msgFrom.displayName + " (" + msgFrom.emailAddress + ")");
}

// Example implementation
function UpdateTaskPaneUI(item) {
  // Assuming that item is always a read item (instead of a compose item).
  if (item != null) console.log(item.subject);
}

function itemChanged(eventArgs) {
  // Update UI based on the new current item
  UpdateTaskPaneUI(Office.context.mailbox.item);
}

**Comment by TCourtneyOwen** [comment]
If we have a way to detect if the taskpane is pinned, which I believe is only supported in Read mode, then we could have getDefaultSaga() in packages/editor/src/pages/Editor/store/solutions make a call to get default boilerplate script that includes the ItemChanged event handler. Currently getDefaultSaga() populates the boilerplate sample code by making a call to get the content of https://github.com/OfficeDev/office-js-snippets/blob/master/samples/outlook/default.yaml.  We could perhaps add to this yaml file to have sample script for the context change scenario and to use that script instead of the current default script when we detect the taskpane is pinned.  But this is all contingent on being able to detect when the taskpane is pinned.  According to this post, that's not possible, but it was written over 1 1/2 years ago:  https://stackoverflow.com/questions/52050254/can-i-know-if-the-task-pane-is-pinned-or-not-in-outlook-web-add-in

**Comment by annich-MS** [comment]
As far as I'm aware, there is still no way to tell if the add-in pane supports pinning. @exextoc would know more.

Alternatively, when we receive an itemChanged message, we could prompt the user if they want to load the pinning sample, that way it only comes up when it matters, rather than trying to plan ahead.

**Comment by exextoc** [comment]
That is correct, there is currently no way to tell if the taskpane is pinned. The only way to know the taskpane is pinned is when the ItemChanged event is fired.
