### ISSUE TITLE
Intellisense is Marking Correct Code Wrong

### ISSUE THREAD

**Issue by areed1192** [OfficeDev/script-lab#735]
When I set a multi-cell range to the same string value, Intellisense is highlighting it as incorrect and notes the following error.

`Type 'string' is not assignable to type 'any[][]'.`

From what I was reading in the documentation this should be a valid way to set multiple cells to the same string value, so I am not sure why it is highlighting it as incorrect.

**Link to Documentation:** https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-core-concepts

**Operating System:** Windows 10
**Windows Build:** 10.0.17763

![image](https://user-images.githubusercontent.com/21281964/57986082-07844b80-7a25-11e9-88d8-1ef29f034c94.png)

**Comment by areed1192** [comment]
Realized that this is a TypeScript compile error and that the workaround is setting `xl.workbook` to `xl.workbook as any`.

**Comment by Zlatkovsky** [comment]
@areed1192 , FWIW, you don't need to cast "workbook as any".  All it's complaining about is that it wants a 2D array for setting values, whereas you are giving it a single value (the fact that it's the workbook name is irrelevant -- it could have been "hello world").  For which you can either:

1. Do `xlRange.values = "Hello World" as any`.  This works because at runtime, we are perfectly happy to accept a single value; it's just that TypeScript doesn't allow more liberal "set" types than "get" types.
2. Put it into a single-value 2D array:  `xlRange.values = [["Hello World"]]`
