### ISSUE TITLE
How to make ajax request in web addin

### ISSUE THREAD

**Issue by chenxizhang** [OfficeDev/script-lab#736]
Hi all

The very simple code as below, looks good. but never works for me with no error message. 

```
 $("#run").click(run);

function run() {
    console.log("get json");


    $.get("http://services.odata.org/V4/Northwind/Northwind.svc/Products").done(function (result) {
        console.log(result);
    }).fail(function (jqXHR, textStatus, errorThrown) {
        console.log(errorThrown);
    });
}

```

**Comment by WrathOfZombies** [comment]
Well the bug is genuine to the fact that we need to show better errors on what's happening within the runner context.

That said, to solve your specific ask, we run our code in an HTTPS domain for security reasons and your code is making an Ajax request to an OData endpoint over HTTP in an HTTPS hosted page, which leads to the browser's web security kicking in, which essentially blocks it and hence the no error thrown (in reality a (blocked: mixed content) error is thrown).

Even if you were to switch to HTTPS, seems that the api, doesn't have a valid certificate which would fail again due to browser web security (another error that we should be showing correctly)

Thanks for reporting..

@Zlatkovsky FYI

**Comment by Zlatkovsky** [comment]
Yep, noted.  I am not sure how much control we have here (and I'm surprised that `$.get` itself doesn't throw a useful error), but we can investigate.  For now, I suggest you use an https endpoint.  There doesn't seem to be a readily-available odata one, but you can find others on the web (e.g.,: https://jsonplaceholder.typicode.com/)

**Comment by chenxizhang** [comment]
thank you @WrathOfZombies  @Zlatkovsky 
I had fix it by use a real https resource.
