### ISSUE TITLE
when i send my snipet url its showing import failed can anybody tell me what is the the problem

### ISSUE THREAD

**Issue by niteshsinghn2** [OfficeDev/script-lab#737]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

## Useful logs

- [ ] Fiddler traces
- [ ] Console errors
- [ ] Screenshots
- [ ] Clip or GIFs

**Comment by Zlatkovsky** [comment]
Can you give an example URL?  Either of the snippet you care about, or of a new snippet if you’d rather not share yours?

**Comment by niteshsinghn2** [comment]
Sir, i can't import the Github Zip Url inside excel script lab.

**Comment by WrathOfZombies** [comment]
@niteshsinghn2, Could you share the url that you are trying to import? Providing that information would help debug the issue.

The reason is that GitHub Zip url has a very different implication that you are trying to use the project's download link on GitHub. So before I confirm/deny I'd need to know what URL you are trying to use.

**Comment by Zlatkovsky** [comment]
Closing due to lack of response...
