### ISSUE TITLE
Script Lab 

### ISSUE THREAD

**Issue by niteshsinghn2** [OfficeDev/script-lab#744]
Hello,

Can anybody tell me when i am trying to import https://github.com/niteshsinghn2/mynewtest inside excel script lab its showing import failed. 

Thank You

**Comment by kbrandl** [comment]
@niteshsinghn2 -- the link that you've posted points to a GitHub repository.  Script Lab is not designed to import a from a GitHub repository.  In Script Lab, you may import a snippet by either of the following methods:
- specifying the a URL of a Gist that was previously created by exporting a snippet from Script Lab (for example, this URL: https://gist.github.com/kbrandl/74e64d74f396cbe6047b3247e3c066d7)

OR

- specifying raw yaml content that's structured in the way that Script Lab expects (for example, the way that the yaml is structured in [this Gist](https://gist.github.com/kbrandl/74e64d74f396cbe6047b3247e3c066d7)).

Also, please note that due to open issue #742, importing external snippets into Script Lab does not currently work on Mac (even if you use one of the methods that I've described above).
